package main

// Auto-generated module registrations
// This file was generated by batch_convert_modules.py

import (
	"fmt"
	"github.com/LaPingvino/recuerdo/internal/core"
	"charskeyboard" "github.com/LaPingvino/recuerdo/internal/modules/charskeyboard"
	"dialogshower" "github.com/LaPingvino/recuerdo/internal/modules/dialogshower"
	"about" "github.com/LaPingvino/recuerdo/internal/modules/about"
	"documentation" "github.com/LaPingvino/recuerdo/internal/modules/documentation"
	"file" "github.com/LaPingvino/recuerdo/internal/modules/file"
	"print" "github.com/LaPingvino/recuerdo/internal/modules/print"
	"results" "github.com/LaPingvino/recuerdo/internal/modules/results"
	"settings" "github.com/LaPingvino/recuerdo/internal/modules/settings"
	"media" "github.com/LaPingvino/recuerdo/internal/modules/media"
	"plaintextwords" "github.com/LaPingvino/recuerdo/internal/modules/plaintextwords"
	"topo" "github.com/LaPingvino/recuerdo/internal/modules/topo"
	"words" "github.com/LaPingvino/recuerdo/internal/modules/words"
	"gui" "github.com/LaPingvino/recuerdo/internal/modules/gui"
	"guiui" "github.com/LaPingvino/recuerdo/internal/modules/guiui"
	"hiddenbrowser" "github.com/LaPingvino/recuerdo/internal/modules/hiddenbrowser"
	"inputtyping" "github.com/LaPingvino/recuerdo/internal/modules/inputtyping"
	"lessondialogs" "github.com/LaPingvino/recuerdo/internal/modules/lessondialogs"
	"media" "github.com/LaPingvino/recuerdo/internal/modules/media"
	"topo" "github.com/LaPingvino/recuerdo/internal/modules/topo"
	"words" "github.com/LaPingvino/recuerdo/internal/modules/words"
	"loadergui" "github.com/LaPingvino/recuerdo/internal/modules/loadergui"
	"mediadisplay" "github.com/LaPingvino/recuerdo/internal/modules/mediadisplay"
	"audio" "github.com/LaPingvino/recuerdo/internal/modules/audio"
	"dailymotion" "github.com/LaPingvino/recuerdo/internal/modules/dailymotion"
	"image" "github.com/LaPingvino/recuerdo/internal/modules/image"
	"liveleak" "github.com/LaPingvino/recuerdo/internal/modules/liveleak"
	"text" "github.com/LaPingvino/recuerdo/internal/modules/text"
	"video" "github.com/LaPingvino/recuerdo/internal/modules/video"
	"vimeo" "github.com/LaPingvino/recuerdo/internal/modules/vimeo"
	"website" "github.com/LaPingvino/recuerdo/internal/modules/website"
	"youtube" "github.com/LaPingvino/recuerdo/internal/modules/youtube"
	"ocrgui" "github.com/LaPingvino/recuerdo/internal/modules/ocrgui"
	"percentnotesviewer" "github.com/LaPingvino/recuerdo/internal/modules/percentnotesviewer"
	"media" "github.com/LaPingvino/recuerdo/internal/modules/media"
	"topo" "github.com/LaPingvino/recuerdo/internal/modules/topo"
	"words" "github.com/LaPingvino/recuerdo/internal/modules/words"
	"printer" "github.com/LaPingvino/recuerdo/internal/modules/printer"
	"progressviewer" "github.com/LaPingvino/recuerdo/internal/modules/progressviewer"
	"qtapp" "github.com/LaPingvino/recuerdo/internal/modules/qtapp"
	"recentlyopenedviewer" "github.com/LaPingvino/recuerdo/internal/modules/recentlyopenedviewer"
	"boolean" "github.com/LaPingvino/recuerdo/internal/modules/boolean"
	"charactertable" "github.com/LaPingvino/recuerdo/internal/modules/charactertable"
	"language" "github.com/LaPingvino/recuerdo/internal/modules/language"
	"longtext" "github.com/LaPingvino/recuerdo/internal/modules/longtext"
	"multioption" "github.com/LaPingvino/recuerdo/internal/modules/multioption"
	"number" "github.com/LaPingvino/recuerdo/internal/modules/number"
	"option" "github.com/LaPingvino/recuerdo/internal/modules/option"
	"password" "github.com/LaPingvino/recuerdo/internal/modules/password"
	"profile" "github.com/LaPingvino/recuerdo/internal/modules/profile"
	"shorttext" "github.com/LaPingvino/recuerdo/internal/modules/shorttext"
	"settingswidgets" "github.com/LaPingvino/recuerdo/internal/modules/settingswidgets"
	"startwidget" "github.com/LaPingvino/recuerdo/internal/modules/startwidget"
	"hangmangraphics" "github.com/LaPingvino/recuerdo/internal/modules/hangmangraphics"
	"hangman" "github.com/LaPingvino/recuerdo/internal/modules/hangman"
	"hangmanword" "github.com/LaPingvino/recuerdo/internal/modules/hangmanword"
	"inmind" "github.com/LaPingvino/recuerdo/internal/modules/inmind"
	"repeatanswer" "github.com/LaPingvino/recuerdo/internal/modules/repeatanswer"
	"shuffleanswer" "github.com/LaPingvino/recuerdo/internal/modules/shuffleanswer"
	"typing" "github.com/LaPingvino/recuerdo/internal/modules/typing"
	"media" "github.com/LaPingvino/recuerdo/internal/modules/media"
	"topo" "github.com/LaPingvino/recuerdo/internal/modules/topo"
	"words" "github.com/LaPingvino/recuerdo/internal/modules/words"
	"menu" "github.com/LaPingvino/recuerdo/internal/modules/menu"
	"studentsview" "github.com/LaPingvino/recuerdo/internal/modules/studentsview"
	"teacher" "github.com/LaPingvino/recuerdo/internal/modules/teacher"
	"teacherpanel" "github.com/LaPingvino/recuerdo/internal/modules/teacherpanel"
	"theme" "github.com/LaPingvino/recuerdo/internal/modules/theme"
	"topomaps" "github.com/LaPingvino/recuerdo/internal/modules/topomaps"
	"keyboard" "github.com/LaPingvino/recuerdo/internal/modules/keyboard"
	"main" "github.com/LaPingvino/recuerdo/internal/modules/main"
	"translator" "github.com/LaPingvino/recuerdo/internal/modules/translator"
	"cyrillic" "github.com/LaPingvino/recuerdo/internal/modules/cyrillic"
	"greek" "github.com/LaPingvino/recuerdo/internal/modules/greek"
	"symbols" "github.com/LaPingvino/recuerdo/internal/modules/symbols"
	"datatypeicons" "github.com/LaPingvino/recuerdo/internal/modules/datatypeicons"
	"africa" "github.com/LaPingvino/recuerdo/internal/modules/africa"
	"asia" "github.com/LaPingvino/recuerdo/internal/modules/asia"
	"europe" "github.com/LaPingvino/recuerdo/internal/modules/europe"
	"latinamerica" "github.com/LaPingvino/recuerdo/internal/modules/latinamerica"
	"usa" "github.com/LaPingvino/recuerdo/internal/modules/usa"
	"world" "github.com/LaPingvino/recuerdo/internal/modules/world"
	"metadata" "github.com/LaPingvino/recuerdo/internal/modules/metadata"
	"openteacherauthors" "github.com/LaPingvino/recuerdo/internal/modules/openteacherauthors"
	"all" "github.com/LaPingvino/recuerdo/internal/modules/all"
	"cli" "github.com/LaPingvino/recuerdo/internal/modules/cli"
	"codecomplexity" "github.com/LaPingvino/recuerdo/internal/modules/codecomplexity"
	"codedocumentation" "github.com/LaPingvino/recuerdo/internal/modules/codedocumentation"
	"generatebusinesscard" "github.com/LaPingvino/recuerdo/internal/modules/generatebusinesscard"
	"generatelanguagecodeguessertable" "github.com/LaPingvino/recuerdo/internal/modules/generatelanguagecodeguessertable"
	"generatemobile" "github.com/LaPingvino/recuerdo/internal/modules/generatemobile"
	"generateweb" "github.com/LaPingvino/recuerdo/internal/modules/generateweb"
	"generatewebsite" "github.com/LaPingvino/recuerdo/internal/modules/generatewebsite"
	"gettranslationauthors" "github.com/LaPingvino/recuerdo/internal/modules/gettranslationauthors"
	"help" "github.com/LaPingvino/recuerdo/internal/modules/help"
	"ircbot" "github.com/LaPingvino/recuerdo/internal/modules/ircbot"
	"modulegraph" "github.com/LaPingvino/recuerdo/internal/modules/modulegraph"
	"packagearch" "github.com/LaPingvino/recuerdo/internal/modules/packagearch"
	"packagedebian" "github.com/LaPingvino/recuerdo/internal/modules/packagedebian"
	"packagemac" "github.com/LaPingvino/recuerdo/internal/modules/packagemac"
	"packagerpm" "github.com/LaPingvino/recuerdo/internal/modules/packagerpm"
	"packagesource" "github.com/LaPingvino/recuerdo/internal/modules/packagesource"
	"packagesourcewithsetup" "github.com/LaPingvino/recuerdo/internal/modules/packagesourcewithsetup"
	"packagewindowsmsi" "github.com/LaPingvino/recuerdo/internal/modules/packagewindowsmsi"
	"packagewindowsportable" "github.com/LaPingvino/recuerdo/internal/modules/packagewindowsportable"
	"selfstudy" "github.com/LaPingvino/recuerdo/internal/modules/selfstudy"
	"shell" "github.com/LaPingvino/recuerdo/internal/modules/shell"
	"studentathome" "github.com/LaPingvino/recuerdo/internal/modules/studentathome"
	"studentatschool" "github.com/LaPingvino/recuerdo/internal/modules/studentatschool"
	"teacher" "github.com/LaPingvino/recuerdo/internal/modules/teacher"
	"updaterosetta" "github.com/LaPingvino/recuerdo/internal/modules/updaterosetta"
	"updatetranslations" "github.com/LaPingvino/recuerdo/internal/modules/updatetranslations"
	"webservicesserver" "github.com/LaPingvino/recuerdo/internal/modules/webservicesserver"
	"wordsonly" "github.com/LaPingvino/recuerdo/internal/modules/wordsonly"
	"userdocumentation" "github.com/LaPingvino/recuerdo/internal/modules/userdocumentation"
	"authors" "github.com/LaPingvino/recuerdo/internal/modules/authors"
	"event" "github.com/LaPingvino/recuerdo/internal/modules/event"
	"execute" "github.com/LaPingvino/recuerdo/internal/modules/execute"
	"friendlytranslationnames" "github.com/LaPingvino/recuerdo/internal/modules/friendlytranslationnames"
	"javascriptwords" "github.com/LaPingvino/recuerdo/internal/modules/javascriptwords"
	"media" "github.com/LaPingvino/recuerdo/internal/modules/media"
	"topo" "github.com/LaPingvino/recuerdo/internal/modules/topo"
	"words" "github.com/LaPingvino/recuerdo/internal/modules/words"
	"foreignknown" "github.com/LaPingvino/recuerdo/internal/modules/foreignknown"
	"bisect" "github.com/LaPingvino/recuerdo/internal/modules/bisect"
	"evaluator" "github.com/LaPingvino/recuerdo/internal/modules/evaluator"
	"event" "github.com/LaPingvino/recuerdo/internal/modules/event"
	"lessontype" "github.com/LaPingvino/recuerdo/internal/modules/lessontype"
	"jquery" "github.com/LaPingvino/recuerdo/internal/modules/jquery"
	"tmpl" "github.com/LaPingvino/recuerdo/internal/modules/tmpl"
	"map" "github.com/LaPingvino/recuerdo/internal/modules/map"
	"sum" "github.com/LaPingvino/recuerdo/internal/modules/sum"
	"translator" "github.com/LaPingvino/recuerdo/internal/modules/translator"
	"weblogicgenerator" "github.com/LaPingvino/recuerdo/internal/modules/weblogicgenerator"
	"javascriptpercentscalculator" "github.com/LaPingvino/recuerdo/internal/modules/javascriptpercentscalculator"
	"languagecodeguesser" "github.com/LaPingvino/recuerdo/internal/modules/languagecodeguesser"
	"languagecodeguessertables" "github.com/LaPingvino/recuerdo/internal/modules/languagecodeguessertables"
	"allonce" "github.com/LaPingvino/recuerdo/internal/modules/allonce"
	"smart" "github.com/LaPingvino/recuerdo/internal/modules/smart"
	"hardwords" "github.com/LaPingvino/recuerdo/internal/modules/hardwords"
	"random" "github.com/LaPingvino/recuerdo/internal/modules/random"
	"reverse" "github.com/LaPingvino/recuerdo/internal/modules/reverse"
	"sort" "github.com/LaPingvino/recuerdo/internal/modules/sort"
	"wordsneveransweredcorrectly" "github.com/LaPingvino/recuerdo/internal/modules/wordsneveransweredcorrectly"
	"loader" "github.com/LaPingvino/recuerdo/internal/modules/loader"
	"abbyy" "github.com/LaPingvino/recuerdo/internal/modules/abbyy"
	"anki" "github.com/LaPingvino/recuerdo/internal/modules/anki"
	"anki2" "github.com/LaPingvino/recuerdo/internal/modules/anki2"
	"apkg" "github.com/LaPingvino/recuerdo/internal/modules/apkg"
	"backpack" "github.com/LaPingvino/recuerdo/internal/modules/backpack"
	"csv" "github.com/LaPingvino/recuerdo/internal/modules/csv"
	"cuecard" "github.com/LaPingvino/recuerdo/internal/modules/cuecard"
	"domingo" "github.com/LaPingvino/recuerdo/internal/modules/domingo"
	"flashqard" "github.com/LaPingvino/recuerdo/internal/modules/flashqard"
	"fmd" "github.com/LaPingvino/recuerdo/internal/modules/fmd"
	"gnuvocabtrain" "github.com/LaPingvino/recuerdo/internal/modules/gnuvocabtrain"
	"granule" "github.com/LaPingvino/recuerdo/internal/modules/granule"
	"jml" "github.com/LaPingvino/recuerdo/internal/modules/jml"
	"jvlt" "github.com/LaPingvino/recuerdo/internal/modules/jvlt"
	"kgm" "github.com/LaPingvino/recuerdo/internal/modules/kgm"
	"kvtml" "github.com/LaPingvino/recuerdo/internal/modules/kvtml"
	"ludem" "github.com/LaPingvino/recuerdo/internal/modules/ludem"
	"mnemosyne" "github.com/LaPingvino/recuerdo/internal/modules/mnemosyne"
	"ot" "github.com/LaPingvino/recuerdo/internal/modules/ot"
	"otmd" "github.com/LaPingvino/recuerdo/internal/modules/otmd"
	"ottp" "github.com/LaPingvino/recuerdo/internal/modules/ottp"
	"otwd" "github.com/LaPingvino/recuerdo/internal/modules/otwd"
	"overhoor" "github.com/LaPingvino/recuerdo/internal/modules/overhoor"
	"ovr" "github.com/LaPingvino/recuerdo/internal/modules/ovr"
	"pauker" "github.com/LaPingvino/recuerdo/internal/modules/pauker"
	"t2k" "github.com/LaPingvino/recuerdo/internal/modules/t2k"
	"teachmaster" "github.com/LaPingvino/recuerdo/internal/modules/teachmaster"
	"voca" "github.com/LaPingvino/recuerdo/internal/modules/voca"
	"vocabularium" "github.com/LaPingvino/recuerdo/internal/modules/vocabularium"
	"vokabeltrainer" "github.com/LaPingvino/recuerdo/internal/modules/vokabeltrainer"
	"vtraintxt" "github.com/LaPingvino/recuerdo/internal/modules/vtraintxt"
	"wrts" "github.com/LaPingvino/recuerdo/internal/modules/wrts"
	"words" "github.com/LaPingvino/recuerdo/internal/modules/words"
	"mimicrytypefaceconverter" "github.com/LaPingvino/recuerdo/internal/modules/mimicrytypefaceconverter"
	"modules" "github.com/LaPingvino/recuerdo/internal/modules/modules"
	"modulestestfiletoimport" "github.com/LaPingvino/recuerdo/internal/modules/modulestestfiletoimport"
	"notecalculatorchooser" "github.com/LaPingvino/recuerdo/internal/modules/notecalculatorchooser"
	"american" "github.com/LaPingvino/recuerdo/internal/modules/american"
	"dutch" "github.com/LaPingvino/recuerdo/internal/modules/dutch"
	"ects" "github.com/LaPingvino/recuerdo/internal/modules/ects"
	"french" "github.com/LaPingvino/recuerdo/internal/modules/french"
	"german" "github.com/LaPingvino/recuerdo/internal/modules/german"
	"american" "github.com/LaPingvino/recuerdo/internal/modules/american"
	"dutch" "github.com/LaPingvino/recuerdo/internal/modules/dutch"
	"ects" "github.com/LaPingvino/recuerdo/internal/modules/ects"
	"french" "github.com/LaPingvino/recuerdo/internal/modules/french"
	"german" "github.com/LaPingvino/recuerdo/internal/modules/german"
	"percents" "github.com/LaPingvino/recuerdo/internal/modules/percents"
	"percents" "github.com/LaPingvino/recuerdo/internal/modules/percents"
	"cuneiformrecognizer" "github.com/LaPingvino/recuerdo/internal/modules/cuneiformrecognizer"
	"tesseractrecognizer" "github.com/LaPingvino/recuerdo/internal/modules/tesseractrecognizer"
	"wordlistloader" "github.com/LaPingvino/recuerdo/internal/modules/wordlistloader"
	"odtsaver" "github.com/LaPingvino/recuerdo/internal/modules/odtsaver"
	"otxxloader" "github.com/LaPingvino/recuerdo/internal/modules/otxxloader"
	"otxxsaver" "github.com/LaPingvino/recuerdo/internal/modules/otxxsaver"
	"percentscalculator" "github.com/LaPingvino/recuerdo/internal/modules/percentscalculator"
	"pyinstallerinterface" "github.com/LaPingvino/recuerdo/internal/modules/pyinstallerinterface"
	"recentlyopened" "github.com/LaPingvino/recuerdo/internal/modules/recentlyopened"
	"media" "github.com/LaPingvino/recuerdo/internal/modules/media"
	"words" "github.com/LaPingvino/recuerdo/internal/modules/words"
	"safehtmlchecker" "github.com/LaPingvino/recuerdo/internal/modules/safehtmlchecker"
	"saver" "github.com/LaPingvino/recuerdo/internal/modules/saver"
	"csv" "github.com/LaPingvino/recuerdo/internal/modules/csv"
	"kvtml" "github.com/LaPingvino/recuerdo/internal/modules/kvtml"
	"latex" "github.com/LaPingvino/recuerdo/internal/modules/latex"
	"libreofficeformats" "github.com/LaPingvino/recuerdo/internal/modules/libreofficeformats"
	"mediahtml" "github.com/LaPingvino/recuerdo/internal/modules/mediahtml"
	"odt" "github.com/LaPingvino/recuerdo/internal/modules/odt"
	"ot" "github.com/LaPingvino/recuerdo/internal/modules/ot"
	"ottp" "github.com/LaPingvino/recuerdo/internal/modules/ottp"
	"otwd" "github.com/LaPingvino/recuerdo/internal/modules/otwd"
	"pdf" "github.com/LaPingvino/recuerdo/internal/modules/pdf"
	"png" "github.com/LaPingvino/recuerdo/internal/modules/png"
	"sylk" "github.com/LaPingvino/recuerdo/internal/modules/sylk"
	"t2k" "github.com/LaPingvino/recuerdo/internal/modules/t2k"
	"topohtml" "github.com/LaPingvino/recuerdo/internal/modules/topohtml"
	"wordshtml" "github.com/LaPingvino/recuerdo/internal/modules/wordshtml"
	"wrts" "github.com/LaPingvino/recuerdo/internal/modules/wrts"
	"settings" "github.com/LaPingvino/recuerdo/internal/modules/settings"
	"settingsfilterer" "github.com/LaPingvino/recuerdo/internal/modules/settingsfilterer"
	"sourcewithsetupsaver" "github.com/LaPingvino/recuerdo/internal/modules/sourcewithsetupsaver"
	"spellchecker" "github.com/LaPingvino/recuerdo/internal/modules/spellchecker"
	"sylksaver" "github.com/LaPingvino/recuerdo/internal/modules/sylksaver"
	"media" "github.com/LaPingvino/recuerdo/internal/modules/media"
	"topo" "github.com/LaPingvino/recuerdo/internal/modules/topo"
	"words" "github.com/LaPingvino/recuerdo/internal/modules/words"
	"builder" "github.com/LaPingvino/recuerdo/internal/modules/builder"
	"jsonwriter" "github.com/LaPingvino/recuerdo/internal/modules/jsonwriter"
	"merger" "github.com/LaPingvino/recuerdo/internal/modules/merger"
	"userdocumentationwrapper" "github.com/LaPingvino/recuerdo/internal/modules/userdocumentationwrapper"
	"composer" "github.com/LaPingvino/recuerdo/internal/modules/composer"
	"composer" "github.com/LaPingvino/recuerdo/internal/modules/composer"
	"parser" "github.com/LaPingvino/recuerdo/internal/modules/parser"
	"checker" "github.com/LaPingvino/recuerdo/internal/modules/checker"
	"composer" "github.com/LaPingvino/recuerdo/internal/modules/composer"
	"checker" "github.com/LaPingvino/recuerdo/internal/modules/checker"
	"composer" "github.com/LaPingvino/recuerdo/internal/modules/composer"
	"parser" "github.com/LaPingvino/recuerdo/internal/modules/parser"
	"parser" "github.com/LaPingvino/recuerdo/internal/modules/parser"
	"impl" "github.com/LaPingvino/recuerdo/internal/modules/impl"
	"topo" "github.com/LaPingvino/recuerdo/internal/modules/topo"
	"words" "github.com/LaPingvino/recuerdo/internal/modules/words"
	"buttonregister" "github.com/LaPingvino/recuerdo/internal/modules/buttonregister"
	"inputtypinglogic" "github.com/LaPingvino/recuerdo/internal/modules/inputtypinglogic"
	"javascriptinputtypinglogic" "github.com/LaPingvino/recuerdo/internal/modules/javascriptinputtypinglogic"
	"lessontracker" "github.com/LaPingvino/recuerdo/internal/modules/lessontracker"
	"typingtutormodel" "github.com/LaPingvino/recuerdo/internal/modules/typingtutormodel"
	"connection" "github.com/LaPingvino/recuerdo/internal/modules/connection"
	"uploader" "github.com/LaPingvino/recuerdo/internal/modules/uploader"
	"courseheroapi" "github.com/LaPingvino/recuerdo/internal/modules/courseheroapi"
	"quizletapi" "github.com/LaPingvino/recuerdo/internal/modules/quizletapi"
	"studystackapi" "github.com/LaPingvino/recuerdo/internal/modules/studystackapi"
	"webservicesserverserverimpl" "github.com/LaPingvino/recuerdo/internal/modules/webservicesserverserverimpl"
	"webservicesserver" "github.com/LaPingvino/recuerdo/internal/modules/webservicesserver"
	"datastore" "github.com/LaPingvino/recuerdo/internal/modules/datastore"
	"interval" "github.com/LaPingvino/recuerdo/internal/modules/interval"
	"modulegraphbuilder" "github.com/LaPingvino/recuerdo/internal/modules/modulegraphbuilder"
	"otmd" "github.com/LaPingvino/recuerdo/internal/modules/otmd"
	"txt" "github.com/LaPingvino/recuerdo/internal/modules/txt"
	"sourcesaver" "github.com/LaPingvino/recuerdo/internal/modules/sourcesaver"
	"webdatabasecouch" "github.com/LaPingvino/recuerdo/internal/modules/webdatabasecouch"
	"webdatabase" "github.com/LaPingvino/recuerdo/internal/modules/webdatabase"
	"parser" "github.com/LaPingvino/recuerdo/internal/modules/parser"
	"backgroundimagegenerator" "github.com/LaPingvino/recuerdo/internal/modules/backgroundimagegenerator"
	"businesscardgenerator" "github.com/LaPingvino/recuerdo/internal/modules/businesscardgenerator"
	"cli" "github.com/LaPingvino/recuerdo/internal/modules/cli"
	"codecomplexity" "github.com/LaPingvino/recuerdo/internal/modules/codecomplexity"
	"codecomplexityimpl" "github.com/LaPingvino/recuerdo/internal/modules/codecomplexityimpl"
	"gettranslationauthors" "github.com/LaPingvino/recuerdo/internal/modules/gettranslationauthors"
	"gtkgui" "github.com/LaPingvino/recuerdo/internal/modules/gtkgui"
	"ircbotbot" "github.com/LaPingvino/recuerdo/internal/modules/ircbotbot"
	"ircbot" "github.com/LaPingvino/recuerdo/internal/modules/ircbot"
	"languagecodeguessertablegenerator" "github.com/LaPingvino/recuerdo/internal/modules/languagecodeguessertablegenerator"
	"modulegraph" "github.com/LaPingvino/recuerdo/internal/modules/modulegraph"
	"arch" "github.com/LaPingvino/recuerdo/internal/modules/arch"
	"debian" "github.com/LaPingvino/recuerdo/internal/modules/debian"
	"mac" "github.com/LaPingvino/recuerdo/internal/modules/mac"
	"rpm" "github.com/LaPingvino/recuerdo/internal/modules/rpm"
	"source" "github.com/LaPingvino/recuerdo/internal/modules/source"
	"sourcewithsetup" "github.com/LaPingvino/recuerdo/internal/modules/sourcewithsetup"
	"windowsportable" "github.com/LaPingvino/recuerdo/internal/modules/windowsportable"
	"profileshelp" "github.com/LaPingvino/recuerdo/internal/modules/profileshelp"
	"rosettaupdater" "github.com/LaPingvino/recuerdo/internal/modules/rosettaupdater"
	"shell" "github.com/LaPingvino/recuerdo/internal/modules/shell"
	"jscompress" "github.com/LaPingvino/recuerdo/internal/modules/jscompress"
	"ottestserverauth" "github.com/LaPingvino/recuerdo/internal/modules/ottestserverauth"
	"ottestservermanage" "github.com/LaPingvino/recuerdo/internal/modules/ottestservermanage"
	"ottestserversettings" "github.com/LaPingvino/recuerdo/internal/modules/ottestserversettings"
	"testserverforms" "github.com/LaPingvino/recuerdo/internal/modules/testserverforms"
	"testservermodels" "github.com/LaPingvino/recuerdo/internal/modules/testservermodels"
	"testserverurls" "github.com/LaPingvino/recuerdo/internal/modules/testserverurls"
	"testserverviews" "github.com/LaPingvino/recuerdo/internal/modules/testserverviews"
	"ottestserverurls" "github.com/LaPingvino/recuerdo/internal/modules/ottestserverurls"
	"testserverserver" "github.com/LaPingvino/recuerdo/internal/modules/testserverserver"
	"translationupdater" "github.com/LaPingvino/recuerdo/internal/modules/translationupdater"
	"uicontroller" "github.com/LaPingvino/recuerdo/internal/modules/uicontroller"
	"webservicesserverrunner" "github.com/LaPingvino/recuerdo/internal/modules/webservicesserverrunner"
)

// RegisterAllConvertedModules registers all auto-converted modules
func RegisterAllConvertedModules(manager *core.Manager) error {
	// Register charskeyboard module
	charskeyboardModule := charskeyboard.NewCharskeyboardModule()
	if err := manager.Register(charskeyboardModule); err != nil {
		return fmt.Errorf("failed to register charskeyboard module: %w", err)
	}

	// Register dialogshower module
	dialogshowerModule := dialogshower.NewDialogshowerModule()
	if err := manager.Register(dialogshowerModule); err != nil {
		return fmt.Errorf("failed to register dialogshower module: %w", err)
	}

	// Register about module
	aboutModule := about.NewAboutModule()
	if err := manager.Register(aboutModule); err != nil {
		return fmt.Errorf("failed to register about module: %w", err)
	}

	// Register documentation module
	documentationModule := documentation.NewDocumentationModule()
	if err := manager.Register(documentationModule); err != nil {
		return fmt.Errorf("failed to register documentation module: %w", err)
	}

	// Register file module
	fileModule := file.NewFileModule()
	if err := manager.Register(fileModule); err != nil {
		return fmt.Errorf("failed to register file module: %w", err)
	}

	// Register print module
	printModule := print.NewPrintModule()
	if err := manager.Register(printModule); err != nil {
		return fmt.Errorf("failed to register print module: %w", err)
	}

	// Register results module
	resultsModule := results.NewResultsModule()
	if err := manager.Register(resultsModule); err != nil {
		return fmt.Errorf("failed to register results module: %w", err)
	}

	// Register settings module
	settingsModule := settings.NewSettingsModule()
	if err := manager.Register(settingsModule); err != nil {
		return fmt.Errorf("failed to register settings module: %w", err)
	}

	// Register media module
	mediaModule := media.NewMediaModule()
	if err := manager.Register(mediaModule); err != nil {
		return fmt.Errorf("failed to register media module: %w", err)
	}

	// Register plaintextwords module
	plaintextwordsModule := plaintextwords.NewPlaintextwordsModule()
	if err := manager.Register(plaintextwordsModule); err != nil {
		return fmt.Errorf("failed to register plaintextwords module: %w", err)
	}

	// Register topo module
	topoModule := topo.NewTopoModule()
	if err := manager.Register(topoModule); err != nil {
		return fmt.Errorf("failed to register topo module: %w", err)
	}

	// Register words module
	wordsModule := words.NewWordsModule()
	if err := manager.Register(wordsModule); err != nil {
		return fmt.Errorf("failed to register words module: %w", err)
	}

	// Register gui module
	guiModule := gui.NewGuiModule()
	if err := manager.Register(guiModule); err != nil {
		return fmt.Errorf("failed to register gui module: %w", err)
	}

	// Register guiUi module
	guiUiModule := guiui.NewGuiuiModule()
	if err := manager.Register(guiUiModule); err != nil {
		return fmt.Errorf("failed to register guiUi module: %w", err)
	}

	// Register hiddenbrowser module
	hiddenbrowserModule := hiddenbrowser.NewHiddenbrowserModule()
	if err := manager.Register(hiddenbrowserModule); err != nil {
		return fmt.Errorf("failed to register hiddenbrowser module: %w", err)
	}

	// Register inputtyping module
	inputtypingModule := inputtyping.NewInputtypingModule()
	if err := manager.Register(inputtypingModule); err != nil {
		return fmt.Errorf("failed to register inputtyping module: %w", err)
	}

	// Register lessondialogs module
	lessondialogsModule := lessondialogs.NewLessondialogsModule()
	if err := manager.Register(lessondialogsModule); err != nil {
		return fmt.Errorf("failed to register lessondialogs module: %w", err)
	}

	// Register media module
	mediaModule := media.NewMediaModule()
	if err := manager.Register(mediaModule); err != nil {
		return fmt.Errorf("failed to register media module: %w", err)
	}

	// Register topo module
	topoModule := topo.NewTopoModule()
	if err := manager.Register(topoModule); err != nil {
		return fmt.Errorf("failed to register topo module: %w", err)
	}

	// Register words module
	wordsModule := words.NewWordsModule()
	if err := manager.Register(wordsModule); err != nil {
		return fmt.Errorf("failed to register words module: %w", err)
	}

	// Register loadergui module
	loaderguiModule := loadergui.NewLoaderguiModule()
	if err := manager.Register(loaderguiModule); err != nil {
		return fmt.Errorf("failed to register loadergui module: %w", err)
	}

	// Register mediadisplay module
	mediadisplayModule := mediadisplay.NewMediadisplayModule()
	if err := manager.Register(mediadisplayModule); err != nil {
		return fmt.Errorf("failed to register mediadisplay module: %w", err)
	}

	// Register audio module
	audioModule := audio.NewAudioModule()
	if err := manager.Register(audioModule); err != nil {
		return fmt.Errorf("failed to register audio module: %w", err)
	}

	// Register dailymotion module
	dailymotionModule := dailymotion.NewDailymotionModule()
	if err := manager.Register(dailymotionModule); err != nil {
		return fmt.Errorf("failed to register dailymotion module: %w", err)
	}

	// Register image module
	imageModule := image.NewImageModule()
	if err := manager.Register(imageModule); err != nil {
		return fmt.Errorf("failed to register image module: %w", err)
	}

	// Register liveleak module
	liveleakModule := liveleak.NewLiveleakModule()
	if err := manager.Register(liveleakModule); err != nil {
		return fmt.Errorf("failed to register liveleak module: %w", err)
	}

	// Register text module
	textModule := text.NewTextModule()
	if err := manager.Register(textModule); err != nil {
		return fmt.Errorf("failed to register text module: %w", err)
	}

	// Register video module
	videoModule := video.NewVideoModule()
	if err := manager.Register(videoModule); err != nil {
		return fmt.Errorf("failed to register video module: %w", err)
	}

	// Register vimeo module
	vimeoModule := vimeo.NewVimeoModule()
	if err := manager.Register(vimeoModule); err != nil {
		return fmt.Errorf("failed to register vimeo module: %w", err)
	}

	// Register website module
	websiteModule := website.NewWebsiteModule()
	if err := manager.Register(websiteModule); err != nil {
		return fmt.Errorf("failed to register website module: %w", err)
	}

	// Register youtube module
	youtubeModule := youtube.NewYoutubeModule()
	if err := manager.Register(youtubeModule); err != nil {
		return fmt.Errorf("failed to register youtube module: %w", err)
	}

	// Register ocrgui module
	ocrguiModule := ocrgui.NewOcrguiModule()
	if err := manager.Register(ocrguiModule); err != nil {
		return fmt.Errorf("failed to register ocrgui module: %w", err)
	}

	// Register percentnotesviewer module
	percentnotesviewerModule := percentnotesviewer.NewPercentnotesviewerModule()
	if err := manager.Register(percentnotesviewerModule); err != nil {
		return fmt.Errorf("failed to register percentnotesviewer module: %w", err)
	}

	// Register media module
	mediaModule := media.NewMediaModule()
	if err := manager.Register(mediaModule); err != nil {
		return fmt.Errorf("failed to register media module: %w", err)
	}

	// Register topo module
	topoModule := topo.NewTopoModule()
	if err := manager.Register(topoModule); err != nil {
		return fmt.Errorf("failed to register topo module: %w", err)
	}

	// Register words module
	wordsModule := words.NewWordsModule()
	if err := manager.Register(wordsModule); err != nil {
		return fmt.Errorf("failed to register words module: %w", err)
	}

	// Register printer module
	printerModule := printer.NewPrinterModule()
	if err := manager.Register(printerModule); err != nil {
		return fmt.Errorf("failed to register printer module: %w", err)
	}

	// Register progressviewer module
	progressviewerModule := progressviewer.NewProgressviewerModule()
	if err := manager.Register(progressviewerModule); err != nil {
		return fmt.Errorf("failed to register progressviewer module: %w", err)
	}

	// Register qtapp module
	qtappModule := qtapp.NewQtappModule()
	if err := manager.Register(qtappModule); err != nil {
		return fmt.Errorf("failed to register qtapp module: %w", err)
	}

	// Register recentlyopenedviewer module
	recentlyopenedviewerModule := recentlyopenedviewer.NewRecentlyopenedviewerModule()
	if err := manager.Register(recentlyopenedviewerModule); err != nil {
		return fmt.Errorf("failed to register recentlyopenedviewer module: %w", err)
	}

	// Register boolean module
	booleanModule := boolean.NewBooleanModule()
	if err := manager.Register(booleanModule); err != nil {
		return fmt.Errorf("failed to register boolean module: %w", err)
	}

	// Register charactertable module
	charactertableModule := charactertable.NewCharactertableModule()
	if err := manager.Register(charactertableModule); err != nil {
		return fmt.Errorf("failed to register charactertable module: %w", err)
	}

	// Register language module
	languageModule := language.NewLanguageModule()
	if err := manager.Register(languageModule); err != nil {
		return fmt.Errorf("failed to register language module: %w", err)
	}

	// Register longtext module
	longtextModule := longtext.NewLongtextModule()
	if err := manager.Register(longtextModule); err != nil {
		return fmt.Errorf("failed to register longtext module: %w", err)
	}

	// Register multioption module
	multioptionModule := multioption.NewMultioptionModule()
	if err := manager.Register(multioptionModule); err != nil {
		return fmt.Errorf("failed to register multioption module: %w", err)
	}

	// Register number module
	numberModule := number.NewNumberModule()
	if err := manager.Register(numberModule); err != nil {
		return fmt.Errorf("failed to register number module: %w", err)
	}

	// Register option module
	optionModule := option.NewOptionModule()
	if err := manager.Register(optionModule); err != nil {
		return fmt.Errorf("failed to register option module: %w", err)
	}

	// Register password module
	passwordModule := password.NewPasswordModule()
	if err := manager.Register(passwordModule); err != nil {
		return fmt.Errorf("failed to register password module: %w", err)
	}

	// Register profile module
	profileModule := profile.NewProfileModule()
	if err := manager.Register(profileModule); err != nil {
		return fmt.Errorf("failed to register profile module: %w", err)
	}

	// Register shorttext module
	shorttextModule := shorttext.NewShorttextModule()
	if err := manager.Register(shorttextModule); err != nil {
		return fmt.Errorf("failed to register shorttext module: %w", err)
	}

	// Register settingswidgets module
	settingswidgetsModule := settingswidgets.NewSettingswidgetsModule()
	if err := manager.Register(settingswidgetsModule); err != nil {
		return fmt.Errorf("failed to register settingswidgets module: %w", err)
	}

	// Register startwidget module
	startwidgetModule := startwidget.NewStartwidgetModule()
	if err := manager.Register(startwidgetModule); err != nil {
		return fmt.Errorf("failed to register startwidget module: %w", err)
	}

	// Register hangmanGraphics module
	hangmanGraphicsModule := hangmangraphics.NewHangmangraphicsModule()
	if err := manager.Register(hangmanGraphicsModule); err != nil {
		return fmt.Errorf("failed to register hangmanGraphics module: %w", err)
	}

	// Register hangman module
	hangmanModule := hangman.NewHangmanModule()
	if err := manager.Register(hangmanModule); err != nil {
		return fmt.Errorf("failed to register hangman module: %w", err)
	}

	// Register hangmanWord module
	hangmanWordModule := hangmanword.NewHangmanwordModule()
	if err := manager.Register(hangmanWordModule); err != nil {
		return fmt.Errorf("failed to register hangmanWord module: %w", err)
	}

	// Register inmind module
	inmindModule := inmind.NewInmindModule()
	if err := manager.Register(inmindModule); err != nil {
		return fmt.Errorf("failed to register inmind module: %w", err)
	}

	// Register repeatanswer module
	repeatanswerModule := repeatanswer.NewRepeatanswerModule()
	if err := manager.Register(repeatanswerModule); err != nil {
		return fmt.Errorf("failed to register repeatanswer module: %w", err)
	}

	// Register shuffleanswer module
	shuffleanswerModule := shuffleanswer.NewShuffleanswerModule()
	if err := manager.Register(shuffleanswerModule); err != nil {
		return fmt.Errorf("failed to register shuffleanswer module: %w", err)
	}

	// Register typing module
	typingModule := typing.NewTypingModule()
	if err := manager.Register(typingModule); err != nil {
		return fmt.Errorf("failed to register typing module: %w", err)
	}

	// Register media module
	mediaModule := media.NewMediaModule()
	if err := manager.Register(mediaModule); err != nil {
		return fmt.Errorf("failed to register media module: %w", err)
	}

	// Register topo module
	topoModule := topo.NewTopoModule()
	if err := manager.Register(topoModule); err != nil {
		return fmt.Errorf("failed to register topo module: %w", err)
	}

	// Register words module
	wordsModule := words.NewWordsModule()
	if err := manager.Register(wordsModule); err != nil {
		return fmt.Errorf("failed to register words module: %w", err)
	}

	// Register menu module
	menuModule := menu.NewMenuModule()
	if err := manager.Register(menuModule); err != nil {
		return fmt.Errorf("failed to register menu module: %w", err)
	}

	// Register studentsview module
	studentsviewModule := studentsview.NewStudentsviewModule()
	if err := manager.Register(studentsviewModule); err != nil {
		return fmt.Errorf("failed to register studentsview module: %w", err)
	}

	// Register teacher module
	teacherModule := teacher.NewTeacherModule()
	if err := manager.Register(teacherModule); err != nil {
		return fmt.Errorf("failed to register teacher module: %w", err)
	}

	// Register teacherpanel module
	teacherpanelModule := teacherpanel.NewTeacherpanelModule()
	if err := manager.Register(teacherpanelModule); err != nil {
		return fmt.Errorf("failed to register teacherpanel module: %w", err)
	}

	// Register theme module
	themeModule := theme.NewThemeModule()
	if err := manager.Register(themeModule); err != nil {
		return fmt.Errorf("failed to register theme module: %w", err)
	}

	// Register topomaps module
	topomapsModule := topomaps.NewTopomapsModule()
	if err := manager.Register(topomapsModule); err != nil {
		return fmt.Errorf("failed to register topomaps module: %w", err)
	}

	// Register keyboard module
	keyboardModule := keyboard.NewKeyboardModule()
	if err := manager.Register(keyboardModule); err != nil {
		return fmt.Errorf("failed to register keyboard module: %w", err)
	}

	// Register main module
	mainModule := main.NewMainModule()
	if err := manager.Register(mainModule); err != nil {
		return fmt.Errorf("failed to register main module: %w", err)
	}

	// Register translator module
	translatorModule := translator.NewTranslatorModule()
	if err := manager.Register(translatorModule); err != nil {
		return fmt.Errorf("failed to register translator module: %w", err)
	}

	// Register cyrillic module
	cyrillicModule := cyrillic.NewCyrillicModule()
	if err := manager.Register(cyrillicModule); err != nil {
		return fmt.Errorf("failed to register cyrillic module: %w", err)
	}

	// Register greek module
	greekModule := greek.NewGreekModule()
	if err := manager.Register(greekModule); err != nil {
		return fmt.Errorf("failed to register greek module: %w", err)
	}

	// Register symbols module
	symbolsModule := symbols.NewSymbolsModule()
	if err := manager.Register(symbolsModule); err != nil {
		return fmt.Errorf("failed to register symbols module: %w", err)
	}

	// Register datatypeicons module
	datatypeiconsModule := datatypeicons.NewDatatypeiconsModule()
	if err := manager.Register(datatypeiconsModule); err != nil {
		return fmt.Errorf("failed to register datatypeicons module: %w", err)
	}

	// Register africa module
	africaModule := africa.NewAfricaModule()
	if err := manager.Register(africaModule); err != nil {
		return fmt.Errorf("failed to register africa module: %w", err)
	}

	// Register asia module
	asiaModule := asia.NewAsiaModule()
	if err := manager.Register(asiaModule); err != nil {
		return fmt.Errorf("failed to register asia module: %w", err)
	}

	// Register europe module
	europeModule := europe.NewEuropeModule()
	if err := manager.Register(europeModule); err != nil {
		return fmt.Errorf("failed to register europe module: %w", err)
	}

	// Register latinamerica module
	latinamericaModule := latinamerica.NewLatinamericaModule()
	if err := manager.Register(latinamericaModule); err != nil {
		return fmt.Errorf("failed to register latinamerica module: %w", err)
	}

	// Register usa module
	usaModule := usa.NewUsaModule()
	if err := manager.Register(usaModule); err != nil {
		return fmt.Errorf("failed to register usa module: %w", err)
	}

	// Register world module
	worldModule := world.NewWorldModule()
	if err := manager.Register(worldModule); err != nil {
		return fmt.Errorf("failed to register world module: %w", err)
	}

	// Register metadata module
	metadataModule := metadata.NewMetadataModule()
	if err := manager.Register(metadataModule); err != nil {
		return fmt.Errorf("failed to register metadata module: %w", err)
	}

	// Register openteacherauthors module
	openteacherauthorsModule := openteacherauthors.NewOpenteacherauthorsModule()
	if err := manager.Register(openteacherauthorsModule); err != nil {
		return fmt.Errorf("failed to register openteacherauthors module: %w", err)
	}

	// Register all module
	allModule := all.NewAllModule()
	if err := manager.Register(allModule); err != nil {
		return fmt.Errorf("failed to register all module: %w", err)
	}

	// Register cli module
	cliModule := cli.NewCliModule()
	if err := manager.Register(cliModule); err != nil {
		return fmt.Errorf("failed to register cli module: %w", err)
	}

	// Register codecomplexity module
	codecomplexityModule := codecomplexity.NewCodecomplexityModule()
	if err := manager.Register(codecomplexityModule); err != nil {
		return fmt.Errorf("failed to register codecomplexity module: %w", err)
	}

	// Register codedocumentation module
	codedocumentationModule := codedocumentation.NewCodedocumentationModule()
	if err := manager.Register(codedocumentationModule); err != nil {
		return fmt.Errorf("failed to register codedocumentation module: %w", err)
	}

	// Register generatebusinesscard module
	generatebusinesscardModule := generatebusinesscard.NewGeneratebusinesscardModule()
	if err := manager.Register(generatebusinesscardModule); err != nil {
		return fmt.Errorf("failed to register generatebusinesscard module: %w", err)
	}

	// Register generatelanguagecodeguessertable module
	generatelanguagecodeguessertableModule := generatelanguagecodeguessertable.NewGeneratelanguagecodeguessertableModule()
	if err := manager.Register(generatelanguagecodeguessertableModule); err != nil {
		return fmt.Errorf("failed to register generatelanguagecodeguessertable module: %w", err)
	}

	// Register generatemobile module
	generatemobileModule := generatemobile.NewGeneratemobileModule()
	if err := manager.Register(generatemobileModule); err != nil {
		return fmt.Errorf("failed to register generatemobile module: %w", err)
	}

	// Register generateweb module
	generatewebModule := generateweb.NewGeneratewebModule()
	if err := manager.Register(generatewebModule); err != nil {
		return fmt.Errorf("failed to register generateweb module: %w", err)
	}

	// Register generatewebsite module
	generatewebsiteModule := generatewebsite.NewGeneratewebsiteModule()
	if err := manager.Register(generatewebsiteModule); err != nil {
		return fmt.Errorf("failed to register generatewebsite module: %w", err)
	}

	// Register gettranslationauthors module
	gettranslationauthorsModule := gettranslationauthors.NewGettranslationauthorsModule()
	if err := manager.Register(gettranslationauthorsModule); err != nil {
		return fmt.Errorf("failed to register gettranslationauthors module: %w", err)
	}

	// Register help module
	helpModule := help.NewHelpModule()
	if err := manager.Register(helpModule); err != nil {
		return fmt.Errorf("failed to register help module: %w", err)
	}

	// Register ircbot module
	ircbotModule := ircbot.NewIrcbotModule()
	if err := manager.Register(ircbotModule); err != nil {
		return fmt.Errorf("failed to register ircbot module: %w", err)
	}

	// Register modulegraph module
	modulegraphModule := modulegraph.NewModulegraphModule()
	if err := manager.Register(modulegraphModule); err != nil {
		return fmt.Errorf("failed to register modulegraph module: %w", err)
	}

	// Register packagearch module
	packagearchModule := packagearch.NewPackagearchModule()
	if err := manager.Register(packagearchModule); err != nil {
		return fmt.Errorf("failed to register packagearch module: %w", err)
	}

	// Register packagedebian module
	packagedebianModule := packagedebian.NewPackagedebianModule()
	if err := manager.Register(packagedebianModule); err != nil {
		return fmt.Errorf("failed to register packagedebian module: %w", err)
	}

	// Register packagemac module
	packagemacModule := packagemac.NewPackagemacModule()
	if err := manager.Register(packagemacModule); err != nil {
		return fmt.Errorf("failed to register packagemac module: %w", err)
	}

	// Register packagerpm module
	packagerpmModule := packagerpm.NewPackagerpmModule()
	if err := manager.Register(packagerpmModule); err != nil {
		return fmt.Errorf("failed to register packagerpm module: %w", err)
	}

	// Register packagesource module
	packagesourceModule := packagesource.NewPackagesourceModule()
	if err := manager.Register(packagesourceModule); err != nil {
		return fmt.Errorf("failed to register packagesource module: %w", err)
	}

	// Register packagesourcewithsetup module
	packagesourcewithsetupModule := packagesourcewithsetup.NewPackagesourcewithsetupModule()
	if err := manager.Register(packagesourcewithsetupModule); err != nil {
		return fmt.Errorf("failed to register packagesourcewithsetup module: %w", err)
	}

	// Register packagewindowsmsi module
	packagewindowsmsiModule := packagewindowsmsi.NewPackagewindowsmsiModule()
	if err := manager.Register(packagewindowsmsiModule); err != nil {
		return fmt.Errorf("failed to register packagewindowsmsi module: %w", err)
	}

	// Register packagewindowsportable module
	packagewindowsportableModule := packagewindowsportable.NewPackagewindowsportableModule()
	if err := manager.Register(packagewindowsportableModule); err != nil {
		return fmt.Errorf("failed to register packagewindowsportable module: %w", err)
	}

	// Register selfstudy module
	selfstudyModule := selfstudy.NewSelfstudyModule()
	if err := manager.Register(selfstudyModule); err != nil {
		return fmt.Errorf("failed to register selfstudy module: %w", err)
	}

	// Register shell module
	shellModule := shell.NewShellModule()
	if err := manager.Register(shellModule); err != nil {
		return fmt.Errorf("failed to register shell module: %w", err)
	}

	// Register studentathome module
	studentathomeModule := studentathome.NewStudentathomeModule()
	if err := manager.Register(studentathomeModule); err != nil {
		return fmt.Errorf("failed to register studentathome module: %w", err)
	}

	// Register studentatschool module
	studentatschoolModule := studentatschool.NewStudentatschoolModule()
	if err := manager.Register(studentatschoolModule); err != nil {
		return fmt.Errorf("failed to register studentatschool module: %w", err)
	}

	// Register teacher module
	teacherModule := teacher.NewTeacherModule()
	if err := manager.Register(teacherModule); err != nil {
		return fmt.Errorf("failed to register teacher module: %w", err)
	}

	// Register updaterosetta module
	updaterosettaModule := updaterosetta.NewUpdaterosettaModule()
	if err := manager.Register(updaterosettaModule); err != nil {
		return fmt.Errorf("failed to register updaterosetta module: %w", err)
	}

	// Register updatetranslations module
	updatetranslationsModule := updatetranslations.NewUpdatetranslationsModule()
	if err := manager.Register(updatetranslationsModule); err != nil {
		return fmt.Errorf("failed to register updatetranslations module: %w", err)
	}

	// Register webservicesserver module
	webservicesserverModule := webservicesserver.NewWebservicesserverModule()
	if err := manager.Register(webservicesserverModule); err != nil {
		return fmt.Errorf("failed to register webservicesserver module: %w", err)
	}

	// Register wordsonly module
	wordsonlyModule := wordsonly.NewWordsonlyModule()
	if err := manager.Register(wordsonlyModule); err != nil {
		return fmt.Errorf("failed to register wordsonly module: %w", err)
	}

	// Register userdocumentation module
	userdocumentationModule := userdocumentation.NewUserdocumentationModule()
	if err := manager.Register(userdocumentationModule); err != nil {
		return fmt.Errorf("failed to register userdocumentation module: %w", err)
	}

	// Register authors module
	authorsModule := authors.NewAuthorsModule()
	if err := manager.Register(authorsModule); err != nil {
		return fmt.Errorf("failed to register authors module: %w", err)
	}

	// Register event module
	eventModule := event.NewEventModule()
	if err := manager.Register(eventModule); err != nil {
		return fmt.Errorf("failed to register event module: %w", err)
	}

	// Register execute module
	executeModule := execute.NewExecuteModule()
	if err := manager.Register(executeModule); err != nil {
		return fmt.Errorf("failed to register execute module: %w", err)
	}

	// Register friendlytranslationnames module
	friendlytranslationnamesModule := friendlytranslationnames.NewFriendlytranslationnamesModule()
	if err := manager.Register(friendlytranslationnamesModule); err != nil {
		return fmt.Errorf("failed to register friendlytranslationnames module: %w", err)
	}

	// Register javascriptwords module
	javascriptwordsModule := javascriptwords.NewJavascriptwordsModule()
	if err := manager.Register(javascriptwordsModule); err != nil {
		return fmt.Errorf("failed to register javascriptwords module: %w", err)
	}

	// Register media module
	mediaModule := media.NewMediaModule()
	if err := manager.Register(mediaModule); err != nil {
		return fmt.Errorf("failed to register media module: %w", err)
	}

	// Register topo module
	topoModule := topo.NewTopoModule()
	if err := manager.Register(topoModule); err != nil {
		return fmt.Errorf("failed to register topo module: %w", err)
	}

	// Register words module
	wordsModule := words.NewWordsModule()
	if err := manager.Register(wordsModule); err != nil {
		return fmt.Errorf("failed to register words module: %w", err)
	}

	// Register foreignknown module
	foreignknownModule := foreignknown.NewForeignknownModule()
	if err := manager.Register(foreignknownModule); err != nil {
		return fmt.Errorf("failed to register foreignknown module: %w", err)
	}

	// Register bisect module
	bisectModule := bisect.NewBisectModule()
	if err := manager.Register(bisectModule); err != nil {
		return fmt.Errorf("failed to register bisect module: %w", err)
	}

	// Register evaluator module
	evaluatorModule := evaluator.NewEvaluatorModule()
	if err := manager.Register(evaluatorModule); err != nil {
		return fmt.Errorf("failed to register evaluator module: %w", err)
	}

	// Register event module
	eventModule := event.NewEventModule()
	if err := manager.Register(eventModule); err != nil {
		return fmt.Errorf("failed to register event module: %w", err)
	}

	// Register lessontype module
	lessontypeModule := lessontype.NewLessontypeModule()
	if err := manager.Register(lessontypeModule); err != nil {
		return fmt.Errorf("failed to register lessontype module: %w", err)
	}

	// Register jquery module
	jqueryModule := jquery.NewJqueryModule()
	if err := manager.Register(jqueryModule); err != nil {
		return fmt.Errorf("failed to register jquery module: %w", err)
	}

	// Register tmpl module
	tmplModule := tmpl.NewTmplModule()
	if err := manager.Register(tmplModule); err != nil {
		return fmt.Errorf("failed to register tmpl module: %w", err)
	}

	// Register map module
	mapModule := map.NewMapModule()
	if err := manager.Register(mapModule); err != nil {
		return fmt.Errorf("failed to register map module: %w", err)
	}

	// Register sum module
	sumModule := sum.NewSumModule()
	if err := manager.Register(sumModule); err != nil {
		return fmt.Errorf("failed to register sum module: %w", err)
	}

	// Register translator module
	translatorModule := translator.NewTranslatorModule()
	if err := manager.Register(translatorModule); err != nil {
		return fmt.Errorf("failed to register translator module: %w", err)
	}

	// Register weblogicgenerator module
	weblogicgeneratorModule := weblogicgenerator.NewWeblogicgeneratorModule()
	if err := manager.Register(weblogicgeneratorModule); err != nil {
		return fmt.Errorf("failed to register weblogicgenerator module: %w", err)
	}

	// Register javascriptpercentscalculator module
	javascriptpercentscalculatorModule := javascriptpercentscalculator.NewJavascriptpercentscalculatorModule()
	if err := manager.Register(javascriptpercentscalculatorModule); err != nil {
		return fmt.Errorf("failed to register javascriptpercentscalculator module: %w", err)
	}

	// Register languagecodeguesser module
	languagecodeguesserModule := languagecodeguesser.NewLanguagecodeguesserModule()
	if err := manager.Register(languagecodeguesserModule); err != nil {
		return fmt.Errorf("failed to register languagecodeguesser module: %w", err)
	}

	// Register languagecodeguesserTables module
	languagecodeguesserTablesModule := languagecodeguessertables.NewLanguagecodeguessertablesModule()
	if err := manager.Register(languagecodeguesserTablesModule); err != nil {
		return fmt.Errorf("failed to register languagecodeguesserTables module: %w", err)
	}

	// Register allonce module
	allonceModule := allonce.NewAllonceModule()
	if err := manager.Register(allonceModule); err != nil {
		return fmt.Errorf("failed to register allonce module: %w", err)
	}

	// Register smart module
	smartModule := smart.NewSmartModule()
	if err := manager.Register(smartModule); err != nil {
		return fmt.Errorf("failed to register smart module: %w", err)
	}

	// Register hardwords module
	hardwordsModule := hardwords.NewHardwordsModule()
	if err := manager.Register(hardwordsModule); err != nil {
		return fmt.Errorf("failed to register hardwords module: %w", err)
	}

	// Register random module
	randomModule := random.NewRandomModule()
	if err := manager.Register(randomModule); err != nil {
		return fmt.Errorf("failed to register random module: %w", err)
	}

	// Register reverse module
	reverseModule := reverse.NewReverseModule()
	if err := manager.Register(reverseModule); err != nil {
		return fmt.Errorf("failed to register reverse module: %w", err)
	}

	// Register sort module
	sortModule := sort.NewSortModule()
	if err := manager.Register(sortModule); err != nil {
		return fmt.Errorf("failed to register sort module: %w", err)
	}

	// Register wordsneveransweredcorrectly module
	wordsneveransweredcorrectlyModule := wordsneveransweredcorrectly.NewWordsneveransweredcorrectlyModule()
	if err := manager.Register(wordsneveransweredcorrectlyModule); err != nil {
		return fmt.Errorf("failed to register wordsneveransweredcorrectly module: %w", err)
	}

	// Register loader module
	loaderModule := loader.NewLoaderModule()
	if err := manager.Register(loaderModule); err != nil {
		return fmt.Errorf("failed to register loader module: %w", err)
	}

	// Register abbyy module
	abbyyModule := abbyy.NewAbbyyModule()
	if err := manager.Register(abbyyModule); err != nil {
		return fmt.Errorf("failed to register abbyy module: %w", err)
	}

	// Register anki module
	ankiModule := anki.NewAnkiModule()
	if err := manager.Register(ankiModule); err != nil {
		return fmt.Errorf("failed to register anki module: %w", err)
	}

	// Register anki2 module
	anki2Module := anki2.NewAnki2Module()
	if err := manager.Register(anki2Module); err != nil {
		return fmt.Errorf("failed to register anki2 module: %w", err)
	}

	// Register apkg module
	apkgModule := apkg.NewApkgModule()
	if err := manager.Register(apkgModule); err != nil {
		return fmt.Errorf("failed to register apkg module: %w", err)
	}

	// Register backpack module
	backpackModule := backpack.NewBackpackModule()
	if err := manager.Register(backpackModule); err != nil {
		return fmt.Errorf("failed to register backpack module: %w", err)
	}

	// Register csv module
	csvModule := csv.NewCsvModule()
	if err := manager.Register(csvModule); err != nil {
		return fmt.Errorf("failed to register csv module: %w", err)
	}

	// Register cuecard module
	cuecardModule := cuecard.NewCuecardModule()
	if err := manager.Register(cuecardModule); err != nil {
		return fmt.Errorf("failed to register cuecard module: %w", err)
	}

	// Register domingo module
	domingoModule := domingo.NewDomingoModule()
	if err := manager.Register(domingoModule); err != nil {
		return fmt.Errorf("failed to register domingo module: %w", err)
	}

	// Register flashqard module
	flashqardModule := flashqard.NewFlashqardModule()
	if err := manager.Register(flashqardModule); err != nil {
		return fmt.Errorf("failed to register flashqard module: %w", err)
	}

	// Register fmd module
	fmdModule := fmd.NewFmdModule()
	if err := manager.Register(fmdModule); err != nil {
		return fmt.Errorf("failed to register fmd module: %w", err)
	}

	// Register gnuvocabtrain module
	gnuvocabtrainModule := gnuvocabtrain.NewGnuvocabtrainModule()
	if err := manager.Register(gnuvocabtrainModule); err != nil {
		return fmt.Errorf("failed to register gnuvocabtrain module: %w", err)
	}

	// Register granule module
	granuleModule := granule.NewGranuleModule()
	if err := manager.Register(granuleModule); err != nil {
		return fmt.Errorf("failed to register granule module: %w", err)
	}

	// Register jml module
	jmlModule := jml.NewJmlModule()
	if err := manager.Register(jmlModule); err != nil {
		return fmt.Errorf("failed to register jml module: %w", err)
	}

	// Register jvlt module
	jvltModule := jvlt.NewJvltModule()
	if err := manager.Register(jvltModule); err != nil {
		return fmt.Errorf("failed to register jvlt module: %w", err)
	}

	// Register kgm module
	kgmModule := kgm.NewKgmModule()
	if err := manager.Register(kgmModule); err != nil {
		return fmt.Errorf("failed to register kgm module: %w", err)
	}

	// Register kvtml module
	kvtmlModule := kvtml.NewKvtmlModule()
	if err := manager.Register(kvtmlModule); err != nil {
		return fmt.Errorf("failed to register kvtml module: %w", err)
	}

	// Register ludem module
	ludemModule := ludem.NewLudemModule()
	if err := manager.Register(ludemModule); err != nil {
		return fmt.Errorf("failed to register ludem module: %w", err)
	}

	// Register mnemosyne module
	mnemosyneModule := mnemosyne.NewMnemosyneModule()
	if err := manager.Register(mnemosyneModule); err != nil {
		return fmt.Errorf("failed to register mnemosyne module: %w", err)
	}

	// Register ot module
	otModule := ot.NewOtModule()
	if err := manager.Register(otModule); err != nil {
		return fmt.Errorf("failed to register ot module: %w", err)
	}

	// Register otmd module
	otmdModule := otmd.NewOtmdModule()
	if err := manager.Register(otmdModule); err != nil {
		return fmt.Errorf("failed to register otmd module: %w", err)
	}

	// Register ottp module
	ottpModule := ottp.NewOttpModule()
	if err := manager.Register(ottpModule); err != nil {
		return fmt.Errorf("failed to register ottp module: %w", err)
	}

	// Register otwd module
	otwdModule := otwd.NewOtwdModule()
	if err := manager.Register(otwdModule); err != nil {
		return fmt.Errorf("failed to register otwd module: %w", err)
	}

	// Register overhoor module
	overhoorModule := overhoor.NewOverhoorModule()
	if err := manager.Register(overhoorModule); err != nil {
		return fmt.Errorf("failed to register overhoor module: %w", err)
	}

	// Register ovr module
	ovrModule := ovr.NewOvrModule()
	if err := manager.Register(ovrModule); err != nil {
		return fmt.Errorf("failed to register ovr module: %w", err)
	}

	// Register pauker module
	paukerModule := pauker.NewPaukerModule()
	if err := manager.Register(paukerModule); err != nil {
		return fmt.Errorf("failed to register pauker module: %w", err)
	}

	// Register t2k module
	t2kModule := t2k.NewT2KModule()
	if err := manager.Register(t2kModule); err != nil {
		return fmt.Errorf("failed to register t2k module: %w", err)
	}

	// Register teachmaster module
	teachmasterModule := teachmaster.NewTeachmasterModule()
	if err := manager.Register(teachmasterModule); err != nil {
		return fmt.Errorf("failed to register teachmaster module: %w", err)
	}

	// Register voca module
	vocaModule := voca.NewVocaModule()
	if err := manager.Register(vocaModule); err != nil {
		return fmt.Errorf("failed to register voca module: %w", err)
	}

	// Register vocabularium module
	vocabulariumModule := vocabularium.NewVocabulariumModule()
	if err := manager.Register(vocabulariumModule); err != nil {
		return fmt.Errorf("failed to register vocabularium module: %w", err)
	}

	// Register vokabeltrainer module
	vokabeltrainerModule := vokabeltrainer.NewVokabeltrainerModule()
	if err := manager.Register(vokabeltrainerModule); err != nil {
		return fmt.Errorf("failed to register vokabeltrainer module: %w", err)
	}

	// Register vtraintxt module
	vtraintxtModule := vtraintxt.NewVtraintxtModule()
	if err := manager.Register(vtraintxtModule); err != nil {
		return fmt.Errorf("failed to register vtraintxt module: %w", err)
	}

	// Register wrts module
	wrtsModule := wrts.NewWrtsModule()
	if err := manager.Register(wrtsModule); err != nil {
		return fmt.Errorf("failed to register wrts module: %w", err)
	}

	// Register words module
	wordsModule := words.NewWordsModule()
	if err := manager.Register(wordsModule); err != nil {
		return fmt.Errorf("failed to register words module: %w", err)
	}

	// Register mimicrytypefaceconverter module
	mimicrytypefaceconverterModule := mimicrytypefaceconverter.NewMimicrytypefaceconverterModule()
	if err := manager.Register(mimicrytypefaceconverterModule); err != nil {
		return fmt.Errorf("failed to register mimicrytypefaceconverter module: %w", err)
	}

	// Register modules module
	modulesModule := modules.NewModulesModule()
	if err := manager.Register(modulesModule); err != nil {
		return fmt.Errorf("failed to register modules module: %w", err)
	}

	// Register modulestestFiletoimport module
	modulestestFiletoimportModule := modulestestfiletoimport.NewModulestestfiletoimportModule()
	if err := manager.Register(modulestestFiletoimportModule); err != nil {
		return fmt.Errorf("failed to register modulestestFiletoimport module: %w", err)
	}

	// Register notecalculatorchooser module
	notecalculatorchooserModule := notecalculatorchooser.NewNotecalculatorchooserModule()
	if err := manager.Register(notecalculatorchooserModule); err != nil {
		return fmt.Errorf("failed to register notecalculatorchooser module: %w", err)
	}

	// Register american module
	americanModule := american.NewAmericanModule()
	if err := manager.Register(americanModule); err != nil {
		return fmt.Errorf("failed to register american module: %w", err)
	}

	// Register dutch module
	dutchModule := dutch.NewDutchModule()
	if err := manager.Register(dutchModule); err != nil {
		return fmt.Errorf("failed to register dutch module: %w", err)
	}

	// Register ects module
	ectsModule := ects.NewEctsModule()
	if err := manager.Register(ectsModule); err != nil {
		return fmt.Errorf("failed to register ects module: %w", err)
	}

	// Register french module
	frenchModule := french.NewFrenchModule()
	if err := manager.Register(frenchModule); err != nil {
		return fmt.Errorf("failed to register french module: %w", err)
	}

	// Register german module
	germanModule := german.NewGermanModule()
	if err := manager.Register(germanModule); err != nil {
		return fmt.Errorf("failed to register german module: %w", err)
	}

	// Register american module
	americanModule := american.NewAmericanModule()
	if err := manager.Register(americanModule); err != nil {
		return fmt.Errorf("failed to register american module: %w", err)
	}

	// Register dutch module
	dutchModule := dutch.NewDutchModule()
	if err := manager.Register(dutchModule); err != nil {
		return fmt.Errorf("failed to register dutch module: %w", err)
	}

	// Register ects module
	ectsModule := ects.NewEctsModule()
	if err := manager.Register(ectsModule); err != nil {
		return fmt.Errorf("failed to register ects module: %w", err)
	}

	// Register french module
	frenchModule := french.NewFrenchModule()
	if err := manager.Register(frenchModule); err != nil {
		return fmt.Errorf("failed to register french module: %w", err)
	}

	// Register german module
	germanModule := german.NewGermanModule()
	if err := manager.Register(germanModule); err != nil {
		return fmt.Errorf("failed to register german module: %w", err)
	}

	// Register percents module
	percentsModule := percents.NewPercentsModule()
	if err := manager.Register(percentsModule); err != nil {
		return fmt.Errorf("failed to register percents module: %w", err)
	}

	// Register percents module
	percentsModule := percents.NewPercentsModule()
	if err := manager.Register(percentsModule); err != nil {
		return fmt.Errorf("failed to register percents module: %w", err)
	}

	// Register cuneiformrecognizer module
	cuneiformrecognizerModule := cuneiformrecognizer.NewCuneiformrecognizerModule()
	if err := manager.Register(cuneiformrecognizerModule); err != nil {
		return fmt.Errorf("failed to register cuneiformrecognizer module: %w", err)
	}

	// Register tesseractrecognizer module
	tesseractrecognizerModule := tesseractrecognizer.NewTesseractrecognizerModule()
	if err := manager.Register(tesseractrecognizerModule); err != nil {
		return fmt.Errorf("failed to register tesseractrecognizer module: %w", err)
	}

	// Register wordlistloader module
	wordlistloaderModule := wordlistloader.NewWordlistloaderModule()
	if err := manager.Register(wordlistloaderModule); err != nil {
		return fmt.Errorf("failed to register wordlistloader module: %w", err)
	}

	// Register odtsaver module
	odtsaverModule := odtsaver.NewOdtsaverModule()
	if err := manager.Register(odtsaverModule); err != nil {
		return fmt.Errorf("failed to register odtsaver module: %w", err)
	}

	// Register otxxloader module
	otxxloaderModule := otxxloader.NewOtxxloaderModule()
	if err := manager.Register(otxxloaderModule); err != nil {
		return fmt.Errorf("failed to register otxxloader module: %w", err)
	}

	// Register otxxsaver module
	otxxsaverModule := otxxsaver.NewOtxxsaverModule()
	if err := manager.Register(otxxsaverModule); err != nil {
		return fmt.Errorf("failed to register otxxsaver module: %w", err)
	}

	// Register percentscalculator module
	percentscalculatorModule := percentscalculator.NewPercentscalculatorModule()
	if err := manager.Register(percentscalculatorModule); err != nil {
		return fmt.Errorf("failed to register percentscalculator module: %w", err)
	}

	// Register pyinstallerinterface module
	pyinstallerinterfaceModule := pyinstallerinterface.NewPyinstallerinterfaceModule()
	if err := manager.Register(pyinstallerinterfaceModule); err != nil {
		return fmt.Errorf("failed to register pyinstallerinterface module: %w", err)
	}

	// Register recentlyopened module
	recentlyopenedModule := recentlyopened.NewRecentlyopenedModule()
	if err := manager.Register(recentlyopenedModule); err != nil {
		return fmt.Errorf("failed to register recentlyopened module: %w", err)
	}

	// Register media module
	mediaModule := media.NewMediaModule()
	if err := manager.Register(mediaModule); err != nil {
		return fmt.Errorf("failed to register media module: %w", err)
	}

	// Register words module
	wordsModule := words.NewWordsModule()
	if err := manager.Register(wordsModule); err != nil {
		return fmt.Errorf("failed to register words module: %w", err)
	}

	// Register safehtmlchecker module
	safehtmlcheckerModule := safehtmlchecker.NewSafehtmlcheckerModule()
	if err := manager.Register(safehtmlcheckerModule); err != nil {
		return fmt.Errorf("failed to register safehtmlchecker module: %w", err)
	}

	// Register saver module
	saverModule := saver.NewSaverModule()
	if err := manager.Register(saverModule); err != nil {
		return fmt.Errorf("failed to register saver module: %w", err)
	}

	// Register csv module
	csvModule := csv.NewCsvModule()
	if err := manager.Register(csvModule); err != nil {
		return fmt.Errorf("failed to register csv module: %w", err)
	}

	// Register kvtml module
	kvtmlModule := kvtml.NewKvtmlModule()
	if err := manager.Register(kvtmlModule); err != nil {
		return fmt.Errorf("failed to register kvtml module: %w", err)
	}

	// Register latex module
	latexModule := latex.NewLatexModule()
	if err := manager.Register(latexModule); err != nil {
		return fmt.Errorf("failed to register latex module: %w", err)
	}

	// Register libreofficeformats module
	libreofficeformatsModule := libreofficeformats.NewLibreofficeformatsModule()
	if err := manager.Register(libreofficeformatsModule); err != nil {
		return fmt.Errorf("failed to register libreofficeformats module: %w", err)
	}

	// Register mediahtml module
	mediahtmlModule := mediahtml.NewMediahtmlModule()
	if err := manager.Register(mediahtmlModule); err != nil {
		return fmt.Errorf("failed to register mediahtml module: %w", err)
	}

	// Register odt module
	odtModule := odt.NewOdtModule()
	if err := manager.Register(odtModule); err != nil {
		return fmt.Errorf("failed to register odt module: %w", err)
	}

	// Register ot module
	otModule := ot.NewOtModule()
	if err := manager.Register(otModule); err != nil {
		return fmt.Errorf("failed to register ot module: %w", err)
	}

	// Register ottp module
	ottpModule := ottp.NewOttpModule()
	if err := manager.Register(ottpModule); err != nil {
		return fmt.Errorf("failed to register ottp module: %w", err)
	}

	// Register otwd module
	otwdModule := otwd.NewOtwdModule()
	if err := manager.Register(otwdModule); err != nil {
		return fmt.Errorf("failed to register otwd module: %w", err)
	}

	// Register pdf module
	pdfModule := pdf.NewPdfModule()
	if err := manager.Register(pdfModule); err != nil {
		return fmt.Errorf("failed to register pdf module: %w", err)
	}

	// Register png module
	pngModule := png.NewPngModule()
	if err := manager.Register(pngModule); err != nil {
		return fmt.Errorf("failed to register png module: %w", err)
	}

	// Register sylk module
	sylkModule := sylk.NewSylkModule()
	if err := manager.Register(sylkModule); err != nil {
		return fmt.Errorf("failed to register sylk module: %w", err)
	}

	// Register t2k module
	t2kModule := t2k.NewT2KModule()
	if err := manager.Register(t2kModule); err != nil {
		return fmt.Errorf("failed to register t2k module: %w", err)
	}

	// Register topohtml module
	topohtmlModule := topohtml.NewTopohtmlModule()
	if err := manager.Register(topohtmlModule); err != nil {
		return fmt.Errorf("failed to register topohtml module: %w", err)
	}

	// Register wordshtml module
	wordshtmlModule := wordshtml.NewWordshtmlModule()
	if err := manager.Register(wordshtmlModule); err != nil {
		return fmt.Errorf("failed to register wordshtml module: %w", err)
	}

	// Register wrts module
	wrtsModule := wrts.NewWrtsModule()
	if err := manager.Register(wrtsModule); err != nil {
		return fmt.Errorf("failed to register wrts module: %w", err)
	}

	// Register settings module
	settingsModule := settings.NewSettingsModule()
	if err := manager.Register(settingsModule); err != nil {
		return fmt.Errorf("failed to register settings module: %w", err)
	}

	// Register settingsfilterer module
	settingsfiltererModule := settingsfilterer.NewSettingsfiltererModule()
	if err := manager.Register(settingsfiltererModule); err != nil {
		return fmt.Errorf("failed to register settingsfilterer module: %w", err)
	}

	// Register sourcewithsetupsaver module
	sourcewithsetupsaverModule := sourcewithsetupsaver.NewSourcewithsetupsaverModule()
	if err := manager.Register(sourcewithsetupsaverModule); err != nil {
		return fmt.Errorf("failed to register sourcewithsetupsaver module: %w", err)
	}

	// Register spellchecker module
	spellcheckerModule := spellchecker.NewSpellcheckerModule()
	if err := manager.Register(spellcheckerModule); err != nil {
		return fmt.Errorf("failed to register spellchecker module: %w", err)
	}

	// Register sylksaver module
	sylksaverModule := sylksaver.NewSylksaverModule()
	if err := manager.Register(sylksaverModule); err != nil {
		return fmt.Errorf("failed to register sylksaver module: %w", err)
	}

	// Register media module
	mediaModule := media.NewMediaModule()
	if err := manager.Register(mediaModule); err != nil {
		return fmt.Errorf("failed to register media module: %w", err)
	}

	// Register topo module
	topoModule := topo.NewTopoModule()
	if err := manager.Register(topoModule); err != nil {
		return fmt.Errorf("failed to register topo module: %w", err)
	}

	// Register words module
	wordsModule := words.NewWordsModule()
	if err := manager.Register(wordsModule); err != nil {
		return fmt.Errorf("failed to register words module: %w", err)
	}

	// Register builder module
	builderModule := builder.NewBuilderModule()
	if err := manager.Register(builderModule); err != nil {
		return fmt.Errorf("failed to register builder module: %w", err)
	}

	// Register jsonwriter module
	jsonwriterModule := jsonwriter.NewJsonwriterModule()
	if err := manager.Register(jsonwriterModule); err != nil {
		return fmt.Errorf("failed to register jsonwriter module: %w", err)
	}

	// Register merger module
	mergerModule := merger.NewMergerModule()
	if err := manager.Register(mergerModule); err != nil {
		return fmt.Errorf("failed to register merger module: %w", err)
	}

	// Register userdocumentationwrapper module
	userdocumentationwrapperModule := userdocumentationwrapper.NewUserdocumentationwrapperModule()
	if err := manager.Register(userdocumentationwrapperModule); err != nil {
		return fmt.Errorf("failed to register userdocumentationwrapper module: %w", err)
	}

	// Register composer module
	composerModule := composer.NewComposerModule()
	if err := manager.Register(composerModule); err != nil {
		return fmt.Errorf("failed to register composer module: %w", err)
	}

	// Register composer module
	composerModule := composer.NewComposerModule()
	if err := manager.Register(composerModule); err != nil {
		return fmt.Errorf("failed to register composer module: %w", err)
	}

	// Register parser module
	parserModule := parser.NewParserModule()
	if err := manager.Register(parserModule); err != nil {
		return fmt.Errorf("failed to register parser module: %w", err)
	}

	// Register checker module
	checkerModule := checker.NewCheckerModule()
	if err := manager.Register(checkerModule); err != nil {
		return fmt.Errorf("failed to register checker module: %w", err)
	}

	// Register composer module
	composerModule := composer.NewComposerModule()
	if err := manager.Register(composerModule); err != nil {
		return fmt.Errorf("failed to register composer module: %w", err)
	}

	// Register checker module
	checkerModule := checker.NewCheckerModule()
	if err := manager.Register(checkerModule); err != nil {
		return fmt.Errorf("failed to register checker module: %w", err)
	}

	// Register composer module
	composerModule := composer.NewComposerModule()
	if err := manager.Register(composerModule); err != nil {
		return fmt.Errorf("failed to register composer module: %w", err)
	}

	// Register parser module
	parserModule := parser.NewParserModule()
	if err := manager.Register(parserModule); err != nil {
		return fmt.Errorf("failed to register parser module: %w", err)
	}

	// Register parser module
	parserModule := parser.NewParserModule()
	if err := manager.Register(parserModule); err != nil {
		return fmt.Errorf("failed to register parser module: %w", err)
	}

	// Register impl module
	implModule := impl.NewImplModule()
	if err := manager.Register(implModule); err != nil {
		return fmt.Errorf("failed to register impl module: %w", err)
	}

	// Register topo module
	topoModule := topo.NewTopoModule()
	if err := manager.Register(topoModule); err != nil {
		return fmt.Errorf("failed to register topo module: %w", err)
	}

	// Register words module
	wordsModule := words.NewWordsModule()
	if err := manager.Register(wordsModule); err != nil {
		return fmt.Errorf("failed to register words module: %w", err)
	}

	// Register buttonregister module
	buttonregisterModule := buttonregister.NewButtonregisterModule()
	if err := manager.Register(buttonregisterModule); err != nil {
		return fmt.Errorf("failed to register buttonregister module: %w", err)
	}

	// Register inputtypinglogic module
	inputtypinglogicModule := inputtypinglogic.NewInputtypinglogicModule()
	if err := manager.Register(inputtypinglogicModule); err != nil {
		return fmt.Errorf("failed to register inputtypinglogic module: %w", err)
	}

	// Register javascriptinputtypinglogic module
	javascriptinputtypinglogicModule := javascriptinputtypinglogic.NewJavascriptinputtypinglogicModule()
	if err := manager.Register(javascriptinputtypinglogicModule); err != nil {
		return fmt.Errorf("failed to register javascriptinputtypinglogic module: %w", err)
	}

	// Register lessontracker module
	lessontrackerModule := lessontracker.NewLessontrackerModule()
	if err := manager.Register(lessontrackerModule); err != nil {
		return fmt.Errorf("failed to register lessontracker module: %w", err)
	}

	// Register typingtutormodel module
	typingtutormodelModule := typingtutormodel.NewTypingtutormodelModule()
	if err := manager.Register(typingtutormodelModule); err != nil {
		return fmt.Errorf("failed to register typingtutormodel module: %w", err)
	}

	// Register connection module
	connectionModule := connection.NewConnectionModule()
	if err := manager.Register(connectionModule); err != nil {
		return fmt.Errorf("failed to register connection module: %w", err)
	}

	// Register uploader module
	uploaderModule := uploader.NewUploaderModule()
	if err := manager.Register(uploaderModule); err != nil {
		return fmt.Errorf("failed to register uploader module: %w", err)
	}

	// Register courseheroapi module
	courseheroapiModule := courseheroapi.NewCourseheroapiModule()
	if err := manager.Register(courseheroapiModule); err != nil {
		return fmt.Errorf("failed to register courseheroapi module: %w", err)
	}

	// Register quizletapi module
	quizletapiModule := quizletapi.NewQuizletapiModule()
	if err := manager.Register(quizletapiModule); err != nil {
		return fmt.Errorf("failed to register quizletapi module: %w", err)
	}

	// Register studystackapi module
	studystackapiModule := studystackapi.NewStudystackapiModule()
	if err := manager.Register(studystackapiModule); err != nil {
		return fmt.Errorf("failed to register studystackapi module: %w", err)
	}

	// Register webservicesserverServerimpl module
	webservicesserverServerimplModule := webservicesserverserverimpl.NewWebservicesserverserverimplModule()
	if err := manager.Register(webservicesserverServerimplModule); err != nil {
		return fmt.Errorf("failed to register webservicesserverServerimpl module: %w", err)
	}

	// Register webservicesserver module
	webservicesserverModule := webservicesserver.NewWebservicesserverModule()
	if err := manager.Register(webservicesserverModule); err != nil {
		return fmt.Errorf("failed to register webservicesserver module: %w", err)
	}

	// Register datastore module
	datastoreModule := datastore.NewDatastoreModule()
	if err := manager.Register(datastoreModule); err != nil {
		return fmt.Errorf("failed to register datastore module: %w", err)
	}

	// Register interval module
	intervalModule := interval.NewIntervalModule()
	if err := manager.Register(intervalModule); err != nil {
		return fmt.Errorf("failed to register interval module: %w", err)
	}

	// Register modulegraphbuilder module
	modulegraphbuilderModule := modulegraphbuilder.NewModulegraphbuilderModule()
	if err := manager.Register(modulegraphbuilderModule); err != nil {
		return fmt.Errorf("failed to register modulegraphbuilder module: %w", err)
	}

	// Register otmd module
	otmdModule := otmd.NewOtmdModule()
	if err := manager.Register(otmdModule); err != nil {
		return fmt.Errorf("failed to register otmd module: %w", err)
	}

	// Register txt module
	txtModule := txt.NewTxtModule()
	if err := manager.Register(txtModule); err != nil {
		return fmt.Errorf("failed to register txt module: %w", err)
	}

	// Register sourcesaver module
	sourcesaverModule := sourcesaver.NewSourcesaverModule()
	if err := manager.Register(sourcesaverModule); err != nil {
		return fmt.Errorf("failed to register sourcesaver module: %w", err)
	}

	// Register webdatabaseCouch module
	webdatabaseCouchModule := webdatabasecouch.NewWebdatabasecouchModule()
	if err := manager.Register(webdatabaseCouchModule); err != nil {
		return fmt.Errorf("failed to register webdatabaseCouch module: %w", err)
	}

	// Register webdatabase module
	webdatabaseModule := webdatabase.NewWebdatabaseModule()
	if err := manager.Register(webdatabaseModule); err != nil {
		return fmt.Errorf("failed to register webdatabase module: %w", err)
	}

	// Register parser module
	parserModule := parser.NewParserModule()
	if err := manager.Register(parserModule); err != nil {
		return fmt.Errorf("failed to register parser module: %w", err)
	}

	// Register backgroundimagegenerator module
	backgroundimagegeneratorModule := backgroundimagegenerator.NewBackgroundimagegeneratorModule()
	if err := manager.Register(backgroundimagegeneratorModule); err != nil {
		return fmt.Errorf("failed to register backgroundimagegenerator module: %w", err)
	}

	// Register businesscardgenerator module
	businesscardgeneratorModule := businesscardgenerator.NewBusinesscardgeneratorModule()
	if err := manager.Register(businesscardgeneratorModule); err != nil {
		return fmt.Errorf("failed to register businesscardgenerator module: %w", err)
	}

	// Register cli module
	cliModule := cli.NewCliModule()
	if err := manager.Register(cliModule); err != nil {
		return fmt.Errorf("failed to register cli module: %w", err)
	}

	// Register codecomplexity module
	codecomplexityModule := codecomplexity.NewCodecomplexityModule()
	if err := manager.Register(codecomplexityModule); err != nil {
		return fmt.Errorf("failed to register codecomplexity module: %w", err)
	}

	// Register codecomplexityImpl module
	codecomplexityImplModule := codecomplexityimpl.NewCodecomplexityimplModule()
	if err := manager.Register(codecomplexityImplModule); err != nil {
		return fmt.Errorf("failed to register codecomplexityImpl module: %w", err)
	}

	// Register gettranslationauthors module
	gettranslationauthorsModule := gettranslationauthors.NewGettranslationauthorsModule()
	if err := manager.Register(gettranslationauthorsModule); err != nil {
		return fmt.Errorf("failed to register gettranslationauthors module: %w", err)
	}

	// Register gtkgui module
	gtkguiModule := gtkgui.NewGtkguiModule()
	if err := manager.Register(gtkguiModule); err != nil {
		return fmt.Errorf("failed to register gtkgui module: %w", err)
	}

	// Register ircbotBot module
	ircbotBotModule := ircbotbot.NewIrcbotbotModule()
	if err := manager.Register(ircbotBotModule); err != nil {
		return fmt.Errorf("failed to register ircbotBot module: %w", err)
	}

	// Register ircbot module
	ircbotModule := ircbot.NewIrcbotModule()
	if err := manager.Register(ircbotModule); err != nil {
		return fmt.Errorf("failed to register ircbot module: %w", err)
	}

	// Register languagecodeguessertablegenerator module
	languagecodeguessertablegeneratorModule := languagecodeguessertablegenerator.NewLanguagecodeguessertablegeneratorModule()
	if err := manager.Register(languagecodeguessertablegeneratorModule); err != nil {
		return fmt.Errorf("failed to register languagecodeguessertablegenerator module: %w", err)
	}

	// Register modulegraph module
	modulegraphModule := modulegraph.NewModulegraphModule()
	if err := manager.Register(modulegraphModule); err != nil {
		return fmt.Errorf("failed to register modulegraph module: %w", err)
	}

	// Register arch module
	archModule := arch.NewArchModule()
	if err := manager.Register(archModule); err != nil {
		return fmt.Errorf("failed to register arch module: %w", err)
	}

	// Register debian module
	debianModule := debian.NewDebianModule()
	if err := manager.Register(debianModule); err != nil {
		return fmt.Errorf("failed to register debian module: %w", err)
	}

	// Register mac module
	macModule := mac.NewMacModule()
	if err := manager.Register(macModule); err != nil {
		return fmt.Errorf("failed to register mac module: %w", err)
	}

	// Register rpm module
	rpmModule := rpm.NewRpmModule()
	if err := manager.Register(rpmModule); err != nil {
		return fmt.Errorf("failed to register rpm module: %w", err)
	}

	// Register source module
	sourceModule := source.NewSourceModule()
	if err := manager.Register(sourceModule); err != nil {
		return fmt.Errorf("failed to register source module: %w", err)
	}

	// Register sourcewithsetup module
	sourcewithsetupModule := sourcewithsetup.NewSourcewithsetupModule()
	if err := manager.Register(sourcewithsetupModule); err != nil {
		return fmt.Errorf("failed to register sourcewithsetup module: %w", err)
	}

	// Register windowsportable module
	windowsportableModule := windowsportable.NewWindowsportableModule()
	if err := manager.Register(windowsportableModule); err != nil {
		return fmt.Errorf("failed to register windowsportable module: %w", err)
	}

	// Register profileshelp module
	profileshelpModule := profileshelp.NewProfileshelpModule()
	if err := manager.Register(profileshelpModule); err != nil {
		return fmt.Errorf("failed to register profileshelp module: %w", err)
	}

	// Register rosettaupdater module
	rosettaupdaterModule := rosettaupdater.NewRosettaupdaterModule()
	if err := manager.Register(rosettaupdaterModule); err != nil {
		return fmt.Errorf("failed to register rosettaupdater module: %w", err)
	}

	// Register shell module
	shellModule := shell.NewShellModule()
	if err := manager.Register(shellModule); err != nil {
		return fmt.Errorf("failed to register shell module: %w", err)
	}

	// Register jsCompress module
	jsCompressModule := jscompress.NewJscompressModule()
	if err := manager.Register(jsCompressModule); err != nil {
		return fmt.Errorf("failed to register jsCompress module: %w", err)
	}

	// Register otTestserverAuth module
	otTestserverAuthModule := ottestserverauth.NewOttestserverauthModule()
	if err := manager.Register(otTestserverAuthModule); err != nil {
		return fmt.Errorf("failed to register otTestserverAuth module: %w", err)
	}

	// Register otTestserverManage module
	otTestserverManageModule := ottestservermanage.NewOttestservermanageModule()
	if err := manager.Register(otTestserverManageModule); err != nil {
		return fmt.Errorf("failed to register otTestserverManage module: %w", err)
	}

	// Register otTestserverSettings module
	otTestserverSettingsModule := ottestserversettings.NewOttestserversettingsModule()
	if err := manager.Register(otTestserverSettingsModule); err != nil {
		return fmt.Errorf("failed to register otTestserverSettings module: %w", err)
	}

	// Register testserverForms module
	testserverFormsModule := testserverforms.NewTestserverformsModule()
	if err := manager.Register(testserverFormsModule); err != nil {
		return fmt.Errorf("failed to register testserverForms module: %w", err)
	}

	// Register testserverModels module
	testserverModelsModule := testservermodels.NewTestservermodelsModule()
	if err := manager.Register(testserverModelsModule); err != nil {
		return fmt.Errorf("failed to register testserverModels module: %w", err)
	}

	// Register testserverUrls module
	testserverUrlsModule := testserverurls.NewTestserverurlsModule()
	if err := manager.Register(testserverUrlsModule); err != nil {
		return fmt.Errorf("failed to register testserverUrls module: %w", err)
	}

	// Register testserverViews module
	testserverViewsModule := testserverviews.NewTestserverviewsModule()
	if err := manager.Register(testserverViewsModule); err != nil {
		return fmt.Errorf("failed to register testserverViews module: %w", err)
	}

	// Register otTestserverUrls module
	otTestserverUrlsModule := ottestserverurls.NewOttestserverurlsModule()
	if err := manager.Register(otTestserverUrlsModule); err != nil {
		return fmt.Errorf("failed to register otTestserverUrls module: %w", err)
	}

	// Register testserverServer module
	testserverServerModule := testserverserver.NewTestserverserverModule()
	if err := manager.Register(testserverServerModule); err != nil {
		return fmt.Errorf("failed to register testserverServer module: %w", err)
	}

	// Register translationupdater module
	translationupdaterModule := translationupdater.NewTranslationupdaterModule()
	if err := manager.Register(translationupdaterModule); err != nil {
		return fmt.Errorf("failed to register translationupdater module: %w", err)
	}

	// Register uicontroller module
	uicontrollerModule := uicontroller.NewUicontrollerModule()
	if err := manager.Register(uicontrollerModule); err != nil {
		return fmt.Errorf("failed to register uicontroller module: %w", err)
	}

	// Register webservicesserverrunner module
	webservicesserverrunnerModule := webservicesserverrunner.NewWebservicesserverrunnerModule()
	if err := manager.Register(webservicesserverrunnerModule); err != nil {
		return fmt.Errorf("failed to register webservicesserverrunner module: %w", err)
	}

	return nil
}